version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      #install dependencies
      - echo installing dependencies
      - npm install
  build:
    commands:
      #build
      - echo building
      - npm run build
artifacts:
  files:
    - "**/*"
  discard:path: no
  base-directory: build
